/* test_aes_ccm.c
 *
 * Copyright (C) 2026 wolfSSL Inc.
 *
 * This file is part of wolfHAL.
 *
 * wolfHAL is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfHAL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

#include <stdint.h>
#include <wolfHAL/wolfHAL.h>
#include "wolfHAL_board.h"
#include "test.h"

static const uint8_t key[32] = {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
    0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F,
};

static const uint8_t nonce[12] = {
    0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7,
    0xB8, 0xB9, 0xBA, 0xBB,
};

static const uint8_t aad[16] = {
    0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7,
    0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF,
};

static const uint8_t plaintext[32] = {
    0xDE, 0xAD, 0xBE, 0xEF, 0xCA, 0xFE, 0xBA, 0xBE,
    0x01, 0x23, 0x45, 0x67, 0x89, 0xAB, 0xCD, 0xEF,
    0xFE, 0xDC, 0xBA, 0x98, 0x76, 0x54, 0x32, 0x10,
    0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77,
};

/* NIST CAVP DVPT256.rsp: Alen=32, Plen=24, Nlen=13, Tlen=16, Count=225 */
static const uint8_t ccmKey[32] = {
    0x31, 0x4A, 0x20, 0x2F, 0x83, 0x6F, 0x9F, 0x25,
    0x7E, 0x22, 0xD8, 0xC1, 0x17, 0x57, 0x83, 0x2A,
    0xE5, 0x13, 0x1D, 0x35, 0x7A, 0x72, 0xDF, 0x88,
    0xF3, 0xEF, 0xF0, 0xFF, 0xCE, 0xE0, 0xDA, 0x4E,
};

static const uint8_t ccmNonce[13] = {
    0xA5, 0x44, 0x21, 0x8D, 0xAD, 0xD3, 0xC1, 0x05,
    0x83, 0xDB, 0x49, 0xCF, 0x39,
};

static const uint8_t ccmAad[32] = {
    0x3C, 0x0E, 0x28, 0x15, 0xD3, 0x7D, 0x84, 0x4F,
    0x7A, 0xC2, 0x40, 0xBA, 0x9D, 0x6E, 0x3A, 0x0B,
    0x2A, 0x86, 0xF7, 0x06, 0xE8, 0x85, 0x95, 0x9E,
    0x09, 0xA1, 0x00, 0x5E, 0x02, 0x4F, 0x69, 0x07,
};

static const uint8_t ccmPt[24] = {
    0xE8, 0xDE, 0x97, 0x0F, 0x6E, 0xE8, 0xE8, 0x0E,
    0xDE, 0x93, 0x35, 0x81, 0xB5, 0xBC, 0xF4, 0xD8,
    0x37, 0xE2, 0xB7, 0x2B, 0xAA, 0x8B, 0x00, 0xC3,
};

static const uint8_t ccmCt[24] = {
    0x8D, 0x34, 0xCD, 0xCA, 0x37, 0xCE, 0x77, 0xBE,
    0x68, 0xF6, 0x5B, 0xAF, 0x33, 0x82, 0xE3, 0x1E,
    0xFA, 0x69, 0x3E, 0x63, 0xF9, 0x14, 0xA7, 0x81,
};

static const uint8_t ccmTag[16] = {
    0x36, 0x7F, 0x30, 0xF2, 0xEA, 0xAD, 0x8C, 0x06,
    0x3C, 0xA5, 0x07, 0x95, 0xAC, 0xD9, 0x02, 0x03,
};

static void Test_AesCcm_Basic(void)
{
    uint8_t ct[32] = {0};
    uint8_t pt[32] = {0};
    uint8_t encTag[16] = {0};
    uint8_t decTag[16] = {0};

    WHAL_ASSERT_EQ(whal_AesCcm_Oneshot(BOARD_AES_CCM_DEV, WHAL_CRYPTO_ENCRYPT,
                                        key, 32,
                                        nonce, sizeof(nonce),
                                        aad, sizeof(aad),
                                        plaintext, ct, sizeof(plaintext),
                                        encTag, sizeof(encTag)),
                   WHAL_SUCCESS);

    WHAL_ASSERT_EQ(whal_AesCcm_Oneshot(BOARD_AES_CCM_DEV, WHAL_CRYPTO_DECRYPT,
                                        key, 32,
                                        nonce, sizeof(nonce),
                                        aad, sizeof(aad),
                                        ct, pt, sizeof(ct),
                                        decTag, sizeof(decTag)),
                   WHAL_SUCCESS);

    WHAL_ASSERT_MEM_EQ(pt, plaintext, sizeof(plaintext));
    WHAL_ASSERT_MEM_EQ(decTag, encTag, sizeof(encTag));
}

static void Test_AesCcm_KnownAnswer(void)
{
    uint8_t ct[24] = {0};
    uint8_t tag[16] = {0};

    WHAL_ASSERT_EQ(whal_AesCcm_Oneshot(BOARD_AES_CCM_DEV, WHAL_CRYPTO_ENCRYPT,
                                        ccmKey, 32,
                                        ccmNonce, sizeof(ccmNonce),
                                        ccmAad, sizeof(ccmAad),
                                        ccmPt, ct, sizeof(ccmPt),
                                        tag, sizeof(tag)),
                   WHAL_SUCCESS);

    WHAL_ASSERT_MEM_EQ(ct, ccmCt, sizeof(ccmCt));
    WHAL_ASSERT_MEM_EQ(tag, ccmTag, sizeof(ccmTag));
}

/* Streaming KAT vectors generated by tests/crypto/gen_test_vectors.py from
 * ccmKey + ccmNonce above, AEAD_PT (50-byte deterministic plaintext) and
 * AEAD_AAD (20-byte deterministic AAD). Re-run the script if these inputs
 * are changed. */
static const uint8_t ccmStreamAad[20] = {
    0x05, 0x10, 0x1B, 0x26, 0x31, 0x3C, 0x47, 0x52,
    0x5D, 0x68, 0x73, 0x7E, 0x89, 0x94, 0x9F, 0xAA,
    0xB5, 0xC0, 0xCB, 0xD6,
};

static const uint8_t ccmStreamPt[50] = {
    0x03, 0x0A, 0x11, 0x18, 0x1F, 0x26, 0x2D, 0x34,
    0x3B, 0x42, 0x49, 0x50, 0x57, 0x5E, 0x65, 0x6C,
    0x73, 0x7A, 0x81, 0x88, 0x8F, 0x96, 0x9D, 0xA4,
    0xAB, 0xB2, 0xB9, 0xC0, 0xC7, 0xCE, 0xD5, 0xDC,
    0xE3, 0xEA, 0xF1, 0xF8, 0xFF, 0x06, 0x0D, 0x14,
    0x1B, 0x22, 0x29, 0x30, 0x37, 0x3E, 0x45, 0x4C,
    0x53, 0x5A,
};

static const uint8_t ccmStreamCt[50] = {
    0x66, 0xE0, 0x4B, 0xDD, 0x46, 0x00, 0xB2, 0x84,
    0x8D, 0x27, 0x27, 0x7E, 0xD1, 0x60, 0x72, 0xAA,
    0xBE, 0xF1, 0x08, 0xC0, 0xDC, 0x09, 0x3A, 0xE6,
    0x3D, 0x4B, 0x0A, 0xD3, 0x2B, 0x24, 0xC4, 0xB7,
    0x1C, 0xC6, 0x63, 0x65, 0x15, 0x4C, 0x41, 0x6F,
    0xA4, 0x00, 0x31, 0xB0, 0x42, 0xDE, 0xFF, 0x95,
    0xAD, 0xA0,
};

static const uint8_t ccmStreamTag[16] = {
    0xD8, 0xBC, 0x77, 0x42, 0xDA, 0xCB, 0x5E, 0xD7,
    0x45, 0xE7, 0xFD, 0xA5, 0x77, 0xD3, 0xC2, 0xA6,
};

static const uint8_t ccmStreamNoAadTag[16] = {
    0xF4, 0xF7, 0xEE, 0x77, 0x41, 0xC8, 0xA0, 0x31,
    0x54, 0x3E, 0xA1, 0x68, 0x5F, 0x0F, 0x7F, 0x89,
};

static const uint8_t ccmStreamNoPtTag[16] = {
    0x89, 0x3C, 0x6D, 0x51, 0x9F, 0x6D, 0xD2, 0x59,
    0xF8, 0xE6, 0xF7, 0x9A, 0xB9, 0x20, 0x56, 0x47,
};

static void Test_AesCcm_Streaming(void)
{
    uint8_t ct[sizeof(ccmStreamPt)] = {0};
    uint8_t tag[16] = {0};
    const size_t split = 32;

    WHAL_ASSERT_EQ(whal_AesCcm_Start(BOARD_AES_CCM_DEV, WHAL_CRYPTO_ENCRYPT,
                                      ccmKey, 32,
                                      ccmNonce, sizeof(ccmNonce),
                                      ccmStreamAad, sizeof(ccmStreamAad),
                                      sizeof(tag), sizeof(ccmStreamPt)),
                   WHAL_SUCCESS);

    WHAL_ASSERT_EQ(whal_AesCcm_Process(BOARD_AES_CCM_DEV,
                                        ccmStreamPt, ct, split),
                   WHAL_SUCCESS);

    WHAL_ASSERT_EQ(whal_AesCcm_Process(BOARD_AES_CCM_DEV,
                                        ccmStreamPt + split, ct + split,
                                        sizeof(ccmStreamPt) - split),
                   WHAL_SUCCESS);

    WHAL_ASSERT_EQ(whal_AesCcm_Finalize(BOARD_AES_CCM_DEV, tag, sizeof(tag)),
                   WHAL_SUCCESS);

    WHAL_ASSERT_MEM_EQ(ct, ccmStreamCt, sizeof(ccmStreamCt));
    WHAL_ASSERT_MEM_EQ(tag, ccmStreamTag, sizeof(ccmStreamTag));
}

static void Test_AesCcm_Streaming_NoAad(void)
{
    uint8_t ct[sizeof(ccmStreamPt)] = {0};
    uint8_t tag[16] = {0};
    const size_t split = 32;

    WHAL_ASSERT_EQ(whal_AesCcm_Start(BOARD_AES_CCM_DEV, WHAL_CRYPTO_ENCRYPT,
                                      ccmKey, 32,
                                      ccmNonce, sizeof(ccmNonce),
                                      NULL, 0,
                                      sizeof(tag), sizeof(ccmStreamPt)),
                   WHAL_SUCCESS);

    WHAL_ASSERT_EQ(whal_AesCcm_Process(BOARD_AES_CCM_DEV,
                                        ccmStreamPt, ct, split),
                   WHAL_SUCCESS);

    WHAL_ASSERT_EQ(whal_AesCcm_Process(BOARD_AES_CCM_DEV,
                                        ccmStreamPt + split, ct + split,
                                        sizeof(ccmStreamPt) - split),
                   WHAL_SUCCESS);

    WHAL_ASSERT_EQ(whal_AesCcm_Finalize(BOARD_AES_CCM_DEV, tag, sizeof(tag)),
                   WHAL_SUCCESS);

    WHAL_ASSERT_MEM_EQ(ct, ccmStreamCt, sizeof(ccmStreamCt));
    WHAL_ASSERT_MEM_EQ(tag, ccmStreamNoAadTag, sizeof(ccmStreamNoAadTag));
}

static void Test_AesCcm_Streaming_NoPayload(void)
{
    uint8_t tag[16] = {0};

    WHAL_ASSERT_EQ(whal_AesCcm_Start(BOARD_AES_CCM_DEV, WHAL_CRYPTO_ENCRYPT,
                                      ccmKey, 32,
                                      ccmNonce, sizeof(ccmNonce),
                                      ccmStreamAad, sizeof(ccmStreamAad),
                                      sizeof(tag), 0),
                   WHAL_SUCCESS);

    WHAL_ASSERT_EQ(whal_AesCcm_Finalize(BOARD_AES_CCM_DEV, tag, sizeof(tag)),
                   WHAL_SUCCESS);

    WHAL_ASSERT_MEM_EQ(tag, ccmStreamNoPtTag, sizeof(ccmStreamNoPtTag));
}

static void Test_AesCcm_Streaming_ThreeCall(void)
{
    uint8_t ct[sizeof(ccmStreamPt)] = {0};
    uint8_t tag[16] = {0};

    WHAL_ASSERT_EQ(whal_AesCcm_Start(BOARD_AES_CCM_DEV, WHAL_CRYPTO_ENCRYPT,
                                      ccmKey, 32,
                                      ccmNonce, sizeof(ccmNonce),
                                      ccmStreamAad, sizeof(ccmStreamAad),
                                      sizeof(tag), sizeof(ccmStreamPt)),
                   WHAL_SUCCESS);

    WHAL_ASSERT_EQ(whal_AesCcm_Process(BOARD_AES_CCM_DEV,
                                        ccmStreamPt, ct, 16),
                   WHAL_SUCCESS);
    WHAL_ASSERT_EQ(whal_AesCcm_Process(BOARD_AES_CCM_DEV,
                                        ccmStreamPt + 16, ct + 16, 16),
                   WHAL_SUCCESS);
    WHAL_ASSERT_EQ(whal_AesCcm_Process(BOARD_AES_CCM_DEV,
                                        ccmStreamPt + 32, ct + 32,
                                        sizeof(ccmStreamPt) - 32),
                   WHAL_SUCCESS);

    WHAL_ASSERT_EQ(whal_AesCcm_Finalize(BOARD_AES_CCM_DEV, tag, sizeof(tag)),
                   WHAL_SUCCESS);

    WHAL_ASSERT_MEM_EQ(ct, ccmStreamCt, sizeof(ccmStreamCt));
    WHAL_ASSERT_MEM_EQ(tag, ccmStreamTag, sizeof(ccmStreamTag));
}

void whal_Test_AesCcm(void)
{
    WHAL_TEST_SUITE_START("aes_ccm");
    WHAL_TEST(Test_AesCcm_Basic);
    WHAL_TEST(Test_AesCcm_KnownAnswer);
    WHAL_TEST(Test_AesCcm_Streaming);
    WHAL_TEST(Test_AesCcm_Streaming_NoAad);
    WHAL_TEST(Test_AesCcm_Streaming_NoPayload);
    WHAL_TEST(Test_AesCcm_Streaming_ThreeCall);
    WHAL_TEST_SUITE_END();
}
