/* test_sha224.c
 *
 * Copyright (C) 2026 wolfSSL Inc.
 *
 * This file is part of wolfHAL.
 *
 * wolfHAL is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfHAL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

#include <stdint.h>
#include <wolfHAL/wolfHAL.h>
#include "wolfHAL_board.h"
#include "test.h"

static const uint8_t hashInput[] = { 'a', 'b', 'c' };

/* NIST FIPS 180-4: SHA-224("abc") */
static const uint8_t sha224Digest[28] = {
    0x23, 0x09, 0x7D, 0x22, 0x34, 0x05, 0xD8, 0x22,
    0x86, 0x42, 0xA4, 0x77, 0xBD, 0xA2, 0x55, 0xB3,
    0x2A, 0xAD, 0xBC, 0xE4, 0xBD, 0xA0, 0xB3, 0xF7,
    0xE3, 0x6C, 0x9D, 0xA7,
};

static void Test_Sha224_KnownAnswer(void)
{
    uint8_t digest[28] = {0};

    WHAL_ASSERT_EQ(whal_Sha224_Oneshot(BOARD_SHA224_DEV,
                                       hashInput, sizeof(hashInput),
                                       digest, sizeof(digest)),
                   WHAL_SUCCESS);

    WHAL_ASSERT_MEM_EQ(digest, sha224Digest, sizeof(sha224Digest));
}

/* Streaming KAT: 100-byte deterministic message, split mid-block.
 * Vectors generated by tests/crypto/gen_test_vectors.py. */
static const uint8_t streamMsg[100] = {
    0x03, 0x0A, 0x11, 0x18, 0x1F, 0x26, 0x2D, 0x34,
    0x3B, 0x42, 0x49, 0x50, 0x57, 0x5E, 0x65, 0x6C,
    0x73, 0x7A, 0x81, 0x88, 0x8F, 0x96, 0x9D, 0xA4,
    0xAB, 0xB2, 0xB9, 0xC0, 0xC7, 0xCE, 0xD5, 0xDC,
    0xE3, 0xEA, 0xF1, 0xF8, 0xFF, 0x06, 0x0D, 0x14,
    0x1B, 0x22, 0x29, 0x30, 0x37, 0x3E, 0x45, 0x4C,
    0x53, 0x5A, 0x61, 0x68, 0x6F, 0x76, 0x7D, 0x84,
    0x8B, 0x92, 0x99, 0xA0, 0xA7, 0xAE, 0xB5, 0xBC,
    0xC3, 0xCA, 0xD1, 0xD8, 0xDF, 0xE6, 0xED, 0xF4,
    0xFB, 0x02, 0x09, 0x10, 0x17, 0x1E, 0x25, 0x2C,
    0x33, 0x3A, 0x41, 0x48, 0x4F, 0x56, 0x5D, 0x64,
    0x6B, 0x72, 0x79, 0x80, 0x87, 0x8E, 0x95, 0x9C,
    0xA3, 0xAA, 0xB1, 0xB8,
};

static const uint8_t sha224StreamDigest[28] = {
    0x59, 0xE3, 0xED, 0x2A, 0xB7, 0x90, 0xB3, 0x91,
    0x25, 0x03, 0x5F, 0x7F, 0xCB, 0x4A, 0x72, 0x3F,
    0x59, 0x58, 0xA9, 0xB7, 0xC2, 0x76, 0x09, 0xF8,
    0x8A, 0x53, 0xB1, 0xBB,
};

static void Test_Sha224_Streaming(void)
{
    uint8_t digest[28] = {0};
    const size_t split = 50;

    WHAL_ASSERT_EQ(whal_Sha224_Start(BOARD_SHA224_DEV), WHAL_SUCCESS);
    WHAL_ASSERT_EQ(whal_Sha224_Process(BOARD_SHA224_DEV, streamMsg, split),
                   WHAL_SUCCESS);
    WHAL_ASSERT_EQ(whal_Sha224_Process(BOARD_SHA224_DEV,
                                       streamMsg + split,
                                       sizeof(streamMsg) - split),
                   WHAL_SUCCESS);
    WHAL_ASSERT_EQ(whal_Sha224_Finalize(BOARD_SHA224_DEV,
                                        digest, sizeof(digest)),
                   WHAL_SUCCESS);

    WHAL_ASSERT_MEM_EQ(digest, sha224StreamDigest, sizeof(sha224StreamDigest));
}

void whal_Test_Sha224(void)
{
    WHAL_TEST_SUITE_START("sha224");
    WHAL_TEST(Test_Sha224_KnownAnswer);
    WHAL_TEST(Test_Sha224_Streaming);
    WHAL_TEST_SUITE_END();
}
