/* test_hmac_sha224.c
 *
 * Copyright (C) 2026 wolfSSL Inc.
 *
 * This file is part of wolfHAL.
 *
 * wolfHAL is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfHAL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

#include <stdint.h>
#include <wolfHAL/wolfHAL.h>
#include "wolfHAL_board.h"
#include "test.h"

/* RFC 2202 / RFC 4231 Test Case 1: HMAC with 20-byte 0x0b key, "Hi There" */
static const uint8_t hmacKey[20] = {
    0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B,
    0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B,
    0x0B, 0x0B, 0x0B, 0x0B,
};

static const uint8_t hmacInput[] = {
    'H', 'i', ' ', 'T', 'h', 'e', 'r', 'e',
};

/* RFC 4231 section 4, Test Case 1 */
static const uint8_t hmacSha224Digest[28] = {
    0x89, 0x6F, 0xB1, 0x12, 0x8A, 0xBB, 0xDF, 0x19,
    0x68, 0x32, 0x10, 0x7C, 0xD4, 0x9D, 0xF3, 0x3F,
    0x47, 0xB4, 0xB1, 0x16, 0x99, 0x12, 0xBA, 0x4F,
    0x53, 0x68, 0x4B, 0x22,
};

static void Test_HmacSha224_KnownAnswer(void)
{
    uint8_t digest[28] = {0};

    WHAL_ASSERT_EQ(whal_HmacSha224_Oneshot(BOARD_HMAC_SHA224_DEV,
                                           hmacKey, sizeof(hmacKey),
                                           hmacInput, sizeof(hmacInput),
                                           digest, sizeof(digest)),
                   WHAL_SUCCESS);

    WHAL_ASSERT_MEM_EQ(digest, hmacSha224Digest, sizeof(hmacSha224Digest));
}

/* Streaming KAT: 100-byte message split mid-block, same hmacKey as above.
 * Vectors generated by tests/crypto/gen_test_vectors.py. */
static const uint8_t hmacStreamMsg[100] = {
    0x03, 0x0A, 0x11, 0x18, 0x1F, 0x26, 0x2D, 0x34,
    0x3B, 0x42, 0x49, 0x50, 0x57, 0x5E, 0x65, 0x6C,
    0x73, 0x7A, 0x81, 0x88, 0x8F, 0x96, 0x9D, 0xA4,
    0xAB, 0xB2, 0xB9, 0xC0, 0xC7, 0xCE, 0xD5, 0xDC,
    0xE3, 0xEA, 0xF1, 0xF8, 0xFF, 0x06, 0x0D, 0x14,
    0x1B, 0x22, 0x29, 0x30, 0x37, 0x3E, 0x45, 0x4C,
    0x53, 0x5A, 0x61, 0x68, 0x6F, 0x76, 0x7D, 0x84,
    0x8B, 0x92, 0x99, 0xA0, 0xA7, 0xAE, 0xB5, 0xBC,
    0xC3, 0xCA, 0xD1, 0xD8, 0xDF, 0xE6, 0xED, 0xF4,
    0xFB, 0x02, 0x09, 0x10, 0x17, 0x1E, 0x25, 0x2C,
    0x33, 0x3A, 0x41, 0x48, 0x4F, 0x56, 0x5D, 0x64,
    0x6B, 0x72, 0x79, 0x80, 0x87, 0x8E, 0x95, 0x9C,
    0xA3, 0xAA, 0xB1, 0xB8,
};

static const uint8_t hmacSha224StreamMac[28] = {
    0x15, 0xED, 0x14, 0xD1, 0x5C, 0x32, 0x35, 0x44,
    0x0A, 0x42, 0x10, 0x73, 0x17, 0x2B, 0x42, 0x93,
    0xD8, 0xFF, 0x04, 0x4F, 0x5F, 0x08, 0x33, 0x14,
    0xB0, 0x34, 0x5A, 0x95,
};

static void Test_HmacSha224_Streaming(void)
{
    uint8_t digest[28] = {0};
    const size_t split = 50;

    WHAL_ASSERT_EQ(whal_HmacSha224_Start(BOARD_HMAC_SHA224_DEV,
                                         hmacKey, sizeof(hmacKey)),
                   WHAL_SUCCESS);
    WHAL_ASSERT_EQ(whal_HmacSha224_Process(BOARD_HMAC_SHA224_DEV,
                                           hmacStreamMsg, split),
                   WHAL_SUCCESS);
    WHAL_ASSERT_EQ(whal_HmacSha224_Process(BOARD_HMAC_SHA224_DEV,
                                           hmacStreamMsg + split,
                                           sizeof(hmacStreamMsg) - split),
                   WHAL_SUCCESS);
    WHAL_ASSERT_EQ(whal_HmacSha224_Finalize(BOARD_HMAC_SHA224_DEV,
                                            digest, sizeof(digest)),
                   WHAL_SUCCESS);

    WHAL_ASSERT_MEM_EQ(digest, hmacSha224StreamMac, sizeof(hmacSha224StreamMac));
}

static const uint8_t hmacUnalignedKey[21] = {
    0x01, 0x0A, 0x13, 0x1C, 0x25, 0x2E, 0x37, 0x40,
    0x49, 0x52, 0x5B, 0x64, 0x6D, 0x76, 0x7F, 0x88,
    0x91, 0x9A, 0xA3, 0xAC, 0xB5,
};

static const uint8_t hmacSha224UnalignedMac[28] = {
    0xDB, 0x52, 0x02, 0xDA, 0xE1, 0x60, 0x9A, 0xED,
    0xF7, 0x28, 0x13, 0x7A, 0x0B, 0x5A, 0xE4, 0x80,
    0x69, 0x08, 0xA5, 0xF7, 0x5B, 0x6A, 0xAB, 0xC4,
    0xA4, 0x22, 0xC0, 0x1D,
};

static void Test_HmacSha224_UnalignedKey(void)
{
    uint8_t digest[28] = {0};
    const size_t split = 3;

    WHAL_ASSERT_EQ(whal_HmacSha224_Oneshot(BOARD_HMAC_SHA224_DEV,
                                           hmacUnalignedKey,
                                           sizeof(hmacUnalignedKey),
                                           hmacInput, sizeof(hmacInput),
                                           digest, sizeof(digest)),
                   WHAL_SUCCESS);
    WHAL_ASSERT_MEM_EQ(digest, hmacSha224UnalignedMac,
                       sizeof(hmacSha224UnalignedMac));

    WHAL_ASSERT_EQ(whal_HmacSha224_Start(BOARD_HMAC_SHA224_DEV,
                                         hmacUnalignedKey,
                                         sizeof(hmacUnalignedKey)),
                   WHAL_SUCCESS);
    WHAL_ASSERT_EQ(whal_HmacSha224_Process(BOARD_HMAC_SHA224_DEV,
                                           hmacInput, split),
                   WHAL_SUCCESS);
    WHAL_ASSERT_EQ(whal_HmacSha224_Process(BOARD_HMAC_SHA224_DEV,
                                           hmacInput + split,
                                           sizeof(hmacInput) - split),
                   WHAL_SUCCESS);
    WHAL_ASSERT_EQ(whal_HmacSha224_Finalize(BOARD_HMAC_SHA224_DEV,
                                            digest, sizeof(digest)),
                   WHAL_SUCCESS);
    WHAL_ASSERT_MEM_EQ(digest, hmacSha224UnalignedMac,
                       sizeof(hmacSha224UnalignedMac));
}

void whal_Test_HmacSha224(void)
{
    WHAL_TEST_SUITE_START("hmac_sha224");
    WHAL_TEST(Test_HmacSha224_KnownAnswer);
    WHAL_TEST(Test_HmacSha224_Streaming);
    WHAL_TEST(Test_HmacSha224_UnalignedKey);
    WHAL_TEST_SUITE_END();
}
